[package]
name = "list"
version = "0.1.3"
authors = ["kiven <kiven.mr@gmail.com>"]
description = "A singly-linked stack like list support peek."
repository = "https://github.com/MrKiven/list"
documentation = "https://docs.rs/list"
license = "MIT"

[dependencies]
